# runs a job at 21:30 to throw dice
apiVersion: batch/v1
kind: CronJob
metadata:
  name: throw-dice-cron-job
spec:
  schedule: "30 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: throw-dice-cron-job
            image: kodekloud/throw-dice
          restartPolicy: OnFailure