# job that runs three jobs in parallel and keeps going til 3 are successful (rolls a 6)
apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
spec:
  template:
    spec:
      containers:
      - name: throw-dice-job
        image: kodekloud/throw-dice
      restartPolicy: Never
  backoffLimit: 25
  completions: 3
  parallelism: 3